Feature/snooze event
openHPI/monitoring-backend pull request #18
Opened 2019-02-11 14:26 UTC by hefowe

Closes #17

2019-02-11 15:19 UTC, hefowe commented
To snooze an alert id (e.g. "cpu:host=release") for 1 hour just send a get request to `http://<kapacitor-ip>/events/<event-id>/snooze`.

2019-02-13 10:51 UTC, friedow requested changes

2019-02-13 10:51 UTC, friedow commented on src/services/EventService.ts
> +      responseData.events.forEach((event: any, index: number, array: any[]) => {
please rename function parameter 'array' to something more descriptive :).

2019-02-13 11:13 UTC, friedow approved these changes

2019-02-13 11:29 UTC, merged